/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.claseprogramcionbook.listacircular;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author SCIS2-18
 */
public class Menu extends javax.swing.JFrame {

    ListaCircular obj = new ListaCircular();

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero = new javax.swing.JTextField();
        agregarInicio = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        extremo = new javax.swing.JButton();
        agregarFinal = new javax.swing.JButton();
        agregarEntre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroKeyTyped(evt);
            }
        });

        agregarInicio.setText("agregar inicio");
        agregarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarInicioActionPerformed(evt);
            }
        });

        mostrar.setText("mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        extremo.setText("Extremos");
        extremo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extremoActionPerformed(evt);
            }
        });

        agregarFinal.setText("agregar final");
        agregarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFinalActionPerformed(evt);
            }
        });

        agregarEntre.setText("agregar entre");
        agregarEntre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEntreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarEntre)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(extremo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agregarFinal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarInicio)
                        .addGap(18, 18, 18)
                        .addComponent(mostrar))
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarInicio)
                    .addComponent(mostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extremo)
                    .addComponent(agregarFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarEntre)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarInicioActionPerformed
        if (numero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el nuevo valor");
            return;
        }else obj.crearLista(Integer.parseInt(numero.getText()));
    }//GEN-LAST:event_agregarInicioActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        obj.mostrar();
    }//GEN-LAST:event_mostrarActionPerformed

    private void extremoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extremoActionPerformed
        obj.mostarExtremos();
    }//GEN-LAST:event_extremoActionPerformed

    private void numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_numeroKeyTyped

    private void agregarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFinalActionPerformed
        if (numero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el nuevo valor");
            return;
        }else obj.agregarFinal(Integer.parseInt(numero.getText()));
    }//GEN-LAST:event_agregarFinalActionPerformed

    private void agregarEntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEntreActionPerformed
        if (numero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el nuevo valor");
            return;
        }else obj.agregarEntreNodo(Integer.parseInt(numero.getText()));
    }//GEN-LAST:event_agregarEntreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarEntre;
    private javax.swing.JButton agregarFinal;
    private javax.swing.JButton agregarInicio;
    private javax.swing.JButton extremo;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextField numero;
    // End of variables declaration//GEN-END:variables
}
